#pragma once

#include "./_impl.hpp"
#include "./_linalg.hpp"
#include "./_root.hpp"
#include "./_specfuncs.hpp"
#include "./freq.hpp"
#include "./svd.hpp"
#include "./gauss.hpp"
#include "./poly.hpp"
#include "./kernel.hpp"
#include "./sve.hpp"
//#include "./basis.hpp"
//#include "./augment.hpp"
//#include "./sampling.hpp"
//#include "./basis_set.hpp"
