"""
Constants used in the SparseIR C API.
"""

# Status codes
COMPUTATION_SUCCESS = 0
GET_IMPL_FAILED = -1
INVALID_DIMENSION = -2
INPUT_DIMENSION_MISMATCH = -3
OUTPUT_DIMENSION_MISMATCH = -4
NOT_SUPPORTED = -5
INVALID_ARGUMENT = -6
INTERNAL_ERROR = -7

# SPIR prefixed constants for compatibility
SPIR_COMPUTATION_SUCCESS = 0
SPIR_GET_IMPL_FAILED = -1
SPIR_INVALID_DIMENSION = -2
SPIR_INPUT_DIMENSION_MISMATCH = -3
SPIR_OUTPUT_DIMENSION_MISMATCH = -4
SPIR_NOT_SUPPORTED = -5
SPIR_INVALID_ARGUMENT = -6
SPIR_INTERNAL_ERROR = -7

# Statistics type constants
SPIR_STATISTICS_FERMIONIC = 1
SPIR_STATISTICS_BOSONIC = 0

# Order type constants
SPIR_ORDER_COLUMN_MAJOR = 1
SPIR_ORDER_ROW_MAJOR = 0

# Make sure these are available at module level
SPIR_ORDER_ROW_MAJOR = 0
SPIR_ORDER_COLUMN_MAJOR = 1

# SVE Twork constants
SPIR_TWORK_FLOAT64 = 0
SPIR_TWORK_FLOAT64X2 = 1
