"""
Auto-generated ctypes bindings from C-API header.
DO NOT EDIT THIS FILE MANUALLY.
Generated by tools/gen_ctypes.py
"""

import ctypes
from ctypes import (
    c_int, c_double, c_int64, c_size_t, c_bool,
    POINTER, c_char_p, Structure,
)

from .ctypes_wrapper import (
    spir_kernel, spir_funcs, spir_basis,
    spir_sampling, spir_sve_result,
)

# Custom complex type (matches core.py definition)
class c_double_complex(Structure):
    """Complex number as ctypes Structure."""
    _fields_ = [("real", ctypes.c_double), ("imag", ctypes.c_double)]

    @property
    def value(self):
        return self.real + 1j * self.imag


# Function prototypes: {name: (restype, [argtypes])}
FUNCTIONS = {
    'spir_basis_clone': ('spir_basis', ['spir_basis']),
    'spir_basis_get_default_matsus': ('c_int', ['spir_basis', 'c_int', 'POINTER(c_int64)']),
    'spir_basis_get_default_matsus_ext': ('c_int', ['spir_basis', 'c_int', 'c_int', 'c_int', 'POINTER(c_int64)', 'POINTER(c_int)']),
    'spir_basis_get_default_taus': ('c_int', ['spir_basis', 'POINTER(c_double)']),
    'spir_basis_get_default_taus_ext': ('c_int', ['spir_basis', 'c_int', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_basis_get_default_ws': ('c_int', ['spir_basis', 'POINTER(c_double)']),
    'spir_basis_get_n_default_matsus': ('c_int', ['spir_basis', 'c_int', 'POINTER(c_int)']),
    'spir_basis_get_n_default_matsus_ext': ('c_int', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int)']),
    'spir_basis_get_n_default_taus': ('c_int', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_n_default_ws': ('c_int', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_singular_values': ('c_int', ['spir_basis', 'POINTER(c_double)']),
    'spir_basis_get_size': ('c_int', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_stats': ('c_int', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_svals': ('c_int', ['spir_basis', 'POINTER(c_double)']),
    'spir_basis_get_u': ('spir_funcs', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_uhat': ('spir_funcs', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_uhat_full': ('spir_funcs', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_get_v': ('spir_funcs', ['spir_basis', 'POINTER(c_int)']),
    'spir_basis_is_assigned': ('c_int', ['spir_basis']),
    'spir_basis_new': ('spir_basis', ['c_int', 'c_double', 'c_double', 'c_double', 'spir_kernel', 'spir_sve_result', 'c_int', 'POINTER(c_int)']),
    'spir_basis_new_from_sve_and_inv_weight': ('spir_basis', ['c_int', 'c_double', 'c_double', 'c_double', 'c_double', 'c_int', 'c_double', 'spir_sve_result', 'spir_funcs', 'c_int', 'POINTER(c_int)']),
    'spir_basis_release': ('None', ['spir_basis']),
    'spir_choose_working_type': ('c_int', ['c_double']),
    'spir_dlr2ir_dd': ('c_int', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_dlr2ir_zz': ('c_int', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double_complex)', 'POINTER(c_double_complex)']),
    'spir_dlr_get_npoles': ('c_int', ['spir_basis', 'POINTER(c_int)']),
    'spir_dlr_get_poles': ('c_int', ['spir_basis', 'POINTER(c_double)']),
    'spir_dlr_new': ('spir_basis', ['spir_basis', 'POINTER(c_int)']),
    'spir_dlr_new_with_poles': ('spir_basis', ['spir_basis', 'c_int', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_funcs_batch_eval': ('c_int', ['spir_funcs', 'c_int', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_funcs_batch_eval_matsu': ('c_int', ['spir_funcs', 'c_int', 'c_int', 'POINTER(c_int64)', 'POINTER(c_double_complex)']),
    'spir_funcs_clone': ('spir_funcs', ['spir_funcs']),
    'spir_funcs_eval': ('c_int', ['spir_funcs', 'c_double', 'POINTER(c_double)']),
    'spir_funcs_eval_matsu': ('c_int', ['spir_funcs', 'c_int64', 'POINTER(c_double_complex)']),
    'spir_funcs_from_piecewise_legendre': ('spir_funcs', ['POINTER(c_double)', 'c_int', 'POINTER(c_double)', 'c_int', 'c_int', 'POINTER(c_int)']),
    'spir_funcs_get_knots': ('c_int', ['spir_funcs', 'POINTER(c_double)']),
    'spir_funcs_get_n_knots': ('c_int', ['spir_funcs', 'POINTER(c_int)']),
    'spir_funcs_get_size': ('c_int', ['spir_funcs', 'POINTER(c_int)']),
    'spir_funcs_get_slice': ('spir_funcs', ['spir_funcs', 'c_int', 'POINTER(c_int)', 'POINTER(c_int)']),
    'spir_funcs_is_assigned': ('c_int', ['spir_funcs']),
    'spir_funcs_release': ('None', ['spir_funcs']),
    'spir_gauss_legendre_rule_piecewise_ddouble': ('c_int', ['c_int', 'POINTER(c_double)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_gauss_legendre_rule_piecewise_double': ('c_int', ['c_int', 'POINTER(c_double)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_ir2dlr_dd': ('c_int', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_ir2dlr_zz': ('c_int', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double_complex)', 'POINTER(c_double_complex)']),
    'spir_kernel_clone': ('spir_kernel', ['spir_kernel']),
    'spir_kernel_get_domain': ('c_int', ['spir_kernel', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_kernel_get_sve_hints_ngauss': ('c_int', ['spir_kernel', 'c_double', 'POINTER(c_int)']),
    'spir_kernel_get_sve_hints_nsvals': ('c_int', ['spir_kernel', 'c_double', 'POINTER(c_int)']),
    'spir_kernel_get_sve_hints_segments_x': ('c_int', ['spir_kernel', 'c_double', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_kernel_get_sve_hints_segments_y': ('c_int', ['spir_kernel', 'c_double', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_kernel_is_assigned': ('c_int', ['spir_kernel']),
    'spir_kernel_release': ('None', ['spir_kernel']),
    'spir_logistic_kernel_new': ('spir_kernel', ['c_double', 'POINTER(c_int)']),
    'spir_matsu_sampling_new': ('spir_sampling', ['spir_basis', 'c_int', 'c_int', 'POINTER(c_int64)', 'POINTER(c_int)']),
    'spir_matsu_sampling_new_with_matrix': ('spir_sampling', ['c_int', 'c_int', 'c_int', 'c_int', 'c_int', 'POINTER(c_int64)', 'POINTER(c_double_complex)', 'POINTER(c_int)']),
    'spir_reg_bose_kernel_new': ('spir_kernel', ['c_double', 'POINTER(c_int)']),
    'spir_sampling_clone': ('spir_sampling', ['spir_sampling']),
    'spir_sampling_eval_dd': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_sampling_eval_dz': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double_complex)']),
    'spir_sampling_eval_zz': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double_complex)', 'POINTER(c_double_complex)']),
    'spir_sampling_fit_dd': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)']),
    'spir_sampling_fit_zd': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double_complex)', 'POINTER(c_double)']),
    'spir_sampling_fit_zz': ('c_int', ['spir_sampling', 'c_int', 'c_int', 'POINTER(c_int)', 'c_int', 'POINTER(c_double_complex)', 'POINTER(c_double_complex)']),
    'spir_sampling_get_cond_num': ('c_int', ['spir_sampling', 'POINTER(c_double)']),
    'spir_sampling_get_matsus': ('c_int', ['spir_sampling', 'POINTER(c_int64)']),
    'spir_sampling_get_npoints': ('c_int', ['spir_sampling', 'POINTER(c_int)']),
    'spir_sampling_get_taus': ('c_int', ['spir_sampling', 'POINTER(c_double)']),
    'spir_sampling_is_assigned': ('c_int', ['spir_sampling']),
    'spir_sampling_release': ('None', ['spir_sampling']),
    'spir_sve_result_clone': ('spir_sve_result', ['spir_sve_result']),
    'spir_sve_result_from_matrix': ('spir_sve_result', ['POINTER(c_double)', 'POINTER(c_double)', 'c_int', 'c_int', 'c_int', 'POINTER(c_double)', 'c_int', 'POINTER(c_double)', 'c_int', 'c_int', 'c_double', 'POINTER(c_int)']),
    'spir_sve_result_from_matrix_centrosymmetric': ('spir_sve_result', ['POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_double)', 'c_int', 'c_int', 'c_int', 'POINTER(c_double)', 'c_int', 'POINTER(c_double)', 'c_int', 'c_int', 'c_double', 'POINTER(c_int)']),
    'spir_sve_result_get_size': ('c_int', ['spir_sve_result', 'POINTER(c_int)']),
    'spir_sve_result_get_svals': ('c_int', ['spir_sve_result', 'POINTER(c_double)']),
    'spir_sve_result_is_assigned': ('c_int', ['spir_sve_result']),
    'spir_sve_result_new': ('spir_sve_result', ['spir_kernel', 'c_double', 'c_int', 'c_int', 'c_int', 'POINTER(c_int)']),
    'spir_sve_result_release': ('None', ['spir_sve_result']),
    'spir_sve_result_truncate': ('spir_sve_result', ['spir_sve_result', 'c_double', 'c_int', 'POINTER(c_int)']),
    'spir_tau_sampling_new': ('spir_sampling', ['spir_basis', 'c_int', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_tau_sampling_new_with_matrix': ('spir_sampling', ['c_int', 'c_int', 'c_int', 'c_int', 'POINTER(c_double)', 'POINTER(c_double)', 'POINTER(c_int)']),
    'spir_uhat_get_default_matsus': ('c_int', ['spir_funcs', 'c_int', 'c_int', 'c_int', 'POINTER(c_int64)', 'POINTER(c_int)']),
}
