"""
Constants used in the SparseIR C API.
"""

# Status codes
COMPUTATION_SUCCESS = 0
GET_IMPL_FAILED = -1
INVALID_DIMENSION = -2
INPUT_DIMENSION_MISMATCH = -3
OUTPUT_DIMENSION_MISMATCH = -4
NOT_SUPPORTED = -5
INVALID_ARGUMENT = -6
INTERNAL_ERROR = -7

# Statistics type constants
STATISTICS_FERMIONIC = 1
STATISTICS_BOSONIC = 0

# Order type constants
ORDER_COLUMN_MAJOR = 1
ORDER_ROW_MAJOR = 0 