/*
# Adapted from https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/polynomial/legendre.py#L832-L914
function legval(x, c::AbstractVector)
    nd = length(c)
    nd ≥ 2 || return last(c)

    c0, c1 = @inbounds c[nd - 1], c[nd]
    @inbounds for j in (nd - 2):-1:1
        k = j / (j + 1)
        c0, c1 = c[j] - c1 * k, c0 + c1 * x * (k + 1)
    end
    return c0 + c1 * x
end

# Adapted from https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/polynomial/legendre.py#L1126-L1176
"""
legvander(x, deg)

Pseudo-Vandermonde matrix of degree `deg`.
"""
function legvander(x::AbstractVector{T}, deg::Integer) where {T}
    deg ≥ 0 || throw(DomainError(deg, "degree needs to be non-negative"))

    v = Matrix{T}(undef, length(x), deg + 1)

    # Use forward recursion to generate the entries. This is not as accurate
    # as reverse recursion in this application but it is more efficient.
    @inbounds begin
        for i in eachindex(x)
            v[i, 1] = one(T)
        end
        if deg > 0
            for i in eachindex(x)
                v[i, 2] = x[i]
            end
            for i in 2:deg
                invi = inv(i)
                @views @. v[:, i + 1] = v[:, i] * x * (2 - invi) - v[:, i - 1] * (1 - invi)
            end
        end
    end

    return v
end

# Adapted from https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/polynomial/legendre.py#L612-L701
"""
    legder
"""
function legder(c::AbstractMatrix{T}, cnt=1) where {T}
    cnt ≥ 0 || throw(DomainError(cnt, "The order of derivation needs to be non-negative"))
    cnt == 0 && return c

    c = copy(c)
    n, m = size(c)
    if cnt ≥ n
        return zeros(T, (1, m))
    else
        @views @inbounds for _ in 1:cnt
            n -= 1
            der = Matrix{T}(undef, n, m)
            for j in n:-1:3
                @. der[j, :] = (2j - 1) * c[j + 1, :]
                @. c[j - 1, :] += c[j + 1, :]
            end
            if n > 1
                @. der[2, :] = 3c[3, :]
            end
            @. der[1, :] = c[2, :]
            c = der
        end
    end
    return c
end
*/

/*
Generated by copilot
*/
#include <Eigen/Dense>
#include <vector>
#include <stdexcept>
#include <iostream>

using namespace std;
using namespace Eigen;

#include <vector>
#include <stdexcept>
#include <iostream>

using namespace std;

template <typename T>
T legval(T x, const vector<T>& c) {
    int nd = c.size();
    if (nd < 2) {
        return c.back();
    }

    T c0 = c[nd - 2];
    T c1 = c[nd - 1];
    for (int j = nd - 3; j >= 0; --j) {
        T k = T(j) / T(j + 1);
        T temp = c0;
        c0 = c[j] - c1 * k;
        c1 = temp + c1 * x * (k + 1);
    }
    return c0 + c1 * x;
}

template <typename T>
Matrix<T, Dynamic, Dynamic> legvander(const vector<T>& x, int deg) {
    if (deg < 0) {
        throw domain_error("degree needs to be non-negative");
    }

    int n = x.size();
    Matrix<T, Dynamic, Dynamic> v(n, deg + 1);

    // Use forward recursion to generate the entries
    for (int i = 0; i < n; ++i) {
        v(i, 0) = T(1);
    }
    if (deg > 0) {
        for (int i = 0; i < n; ++i) {
            v(i, 1) = x[i];
        }
        for (int i = 2; i <= deg; ++i) {
            T invi = T(1) / T(i);
            for (int j = 0; j < n; ++j) {
                v(j, i) = v(j, i - 1) * x[j] * (2 - invi) - v(j, i - 2) * (1 - invi);
            }
        }
    }

    return v;
}

#include <Eigen/Dense>
#include <vector>
#include <stdexcept>
#include <iostream>

using namespace std;
using namespace Eigen;

template <typename T>
Matrix<T, Dynamic, Dynamic> legder(Matrix<T, Dynamic, Dynamic> c, int cnt = 1) {
    if (cnt < 0) {
        throw domain_error("The order of derivation needs to be non-negative");
    }
    if (cnt == 0) {
        return c;
    }

    int n = c.rows();
    int m = c.cols();
    if (cnt >= n) {
        return Matrix<T, Dynamic, Dynamic>::Zero(1, m);
    }

    for (int k = 0; k < cnt; ++k) {
        n -= 1;
        Matrix<T, Dynamic, Dynamic> der(n, m);
        for (int j = n; j >= 2; --j) {
            der.row(j - 1) = (2 * j - 1) * c.row(j);
            c.row(j - 2) += c.row(j);
        }
        if (n > 1) {
            der.row(1) = 3 * c.row(2);
        }
        der.row(0) = c.row(1);
        c = der;
    }
    return c;
}