{% set name = "pylibsparseir" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  script: |
    export SPARSEIR_USE_BLAS=1
    cd ${SRC_DIR}/python
    ${PYTHON} setup.py install --single-version-externally-managed --record=record.txt
    # Ensure the shared library is copied to the correct location
    if [ -f "${SRC_DIR}/build/lib/libsparseir.dylib" ]; then
      cp "${SRC_DIR}/build/lib/libsparseir.dylib" "${PREFIX}/lib/"
    elif [ -f "${SRC_DIR}/build/lib/libsparseir.so" ]; then
      cp "${SRC_DIR}/build/lib/libsparseir.so" "${PREFIX}/lib/"
    fi
  files:
    - lib/python3.*/site-packages/pylibsparseir/
    - lib/python3.*/site-packages/pylibsparseir-*.egg-info/
    - bin/clean
    - lib/libsparseir.*
    - lib/python3.*/site-packages/libsparseir.*

requirements:
  build:
    - python >=3.10
    - setuptools >=77.0.0
    - wheel
    - packaging >=24.2
    - cmake >=3.25
    - scikit-build
    - ninja
    - make
    - {{ compiler('cxx') }}
  host:
    - python >=3.10
    - numpy
    - scipy
    - eigen
    - openblas  # [unix]
    - mkl  # [win]
  run:
    - python >=3.10
    - numpy
    - scipy
    - {{ pin_compatible('eigen') }}

test:
  imports:
    - pylibsparseir
  commands:
    - python -c "import pylibsparseir; print('pylibsparseir imported successfully')"
    - test -f ${PREFIX}/lib/libsparseir.dylib  # [osx]
    - test -f ${PREFIX}/lib/libsparseir.so     # [linux]
    - test -f ${PREFIX}/lib/libsparseir.dll    # [win]

about:
  home: https://github.com/SpM-lab/libsparseir
  license: MIT
  license_file: LICENSE
  summary: Python bindings for the libsparseir library, providing efficient sparse intermediate representation for many-body physics calculations
  description: |
    pylibsparseir provides Python bindings for the libsparseir C++ library, 
    enabling efficient computation of sparse intermediate representation (IR) 
    basis functions used in many-body physics calculations. It provides 
    efficient computation of Green's functions and other physical quantities.
  doc_url: https://github.com/SpM-lab/libsparseir
  dev_url: https://github.com/SpM-lab/libsparseir

extra:
  recipe-maintainers:
    - SpM-lab
