#!/usr/bin/env python3
"""
Auto-generate dlr2ir_impl.inc file for Fortran module.

This script generates dlr2ir functions for 1d to 7d arrays
based on the template in sparseir_ext_expanded_fixed2.F90.
"""

import os

def generate_shape_string(ndim):
    """Generate shape string for given dimension."""
    if ndim == 1:
        return "(:)"
    elif ndim == 2:
        return "(:,:)"
    elif ndim == 3:
        return "(:,:,:)"
    elif ndim == 4:
        return "(:,:,:,:)"
    elif ndim == 5:
        return "(:,:,:,:,:)"
    elif ndim == 6:
        return "(:,:,:,:,:,:)"
    elif ndim == 7:
        return "(:,:,:,:,:,:,:)"
    else:
        raise ValueError(f"Unsupported dimension: {ndim}")

def generate_dlr2ir_function(ndim, input_type, output_type):
    """Generate dlr2ir function for given dimension and type combination."""
    shape_str = generate_shape_string(ndim)
    
    # Generate dimension array declaration
    dim_array_decl = f"INTEGER(KIND=c_int), TARGET :: input_dims_c({ndim}), output_dims_c({ndim})"
    
    # Determine types and C function
    func_suffix = f"{input_type}{output_type}"
    
    # Input type
    if input_type == 'z':
        input_fortran_type = "COMPLEX(KIND=DP)"
    elif input_type == 'd':
        input_fortran_type = "REAL(KIND=DP)"
    else:
        raise ValueError(f"Unsupported input type: {input_type}")
    
    # Output type
    if output_type == 'z':
        output_fortran_type = "COMPLEX(KIND=DP)"
    elif output_type == 'd':
        output_fortran_type = "REAL(KIND=DP)"
    else:
        raise ValueError(f"Unsupported output type: {output_type}")
    
    # C function
    c_function = f"c_spir_dlr2ir_{func_suffix}"
    
    # Generate the function
    function = f"""SUBROUTINE dlr2ir_{func_suffix}_{ndim}d(obj, target_dim, arr, res)
  TYPE(IR), INTENT(IN) :: obj
  INTEGER, INTENT(IN) :: target_dim
  {input_fortran_type}, INTENT(IN), TARGET :: arr {shape_str}
  {output_fortran_type}, INTENT(OUT), TARGET :: res {shape_str}

  INTEGER(KIND=c_int) :: ndim_c, target_dim_c, status_c
  {dim_array_decl}
  input_dims_c = SHAPE(arr)
  output_dims_c = SHAPE(res)
  ndim_c = {ndim}
  IF (target_dim < 1 .or. target_dim > {ndim}) THEN
    CALL errore('dlr2ir_{func_suffix}_{ndim}d', 'Target dimension is out of range', 1)
  ENDIF
  IF (.NOT. check_output_dims(target_dim, input_dims_c, output_dims_c)) THEN
    CALL errore('dlr2ir_{func_suffix}_{ndim}d', &
        'Output dimensions are not the same as the input dimensions except for the TARGET dimension', 1)
  ENDIF
  IF (SIZE(arr, target_dim) /= obj%npoles) THEN
    CALL errore('dlr2ir_{func_suffix}_{ndim}d', 'Input dimension is not the same as the number of poles', 1)
  ENDIF
  IF (SIZE(res, target_dim) /= obj%size) THEN
     CALL errore('dlr2ir_{func_suffix}_{ndim}d', 'Output dimension is not the same as the size of the IR', 1)
  ENDIF
  target_dim_c = target_dim - 1

  status_c = {c_function}(obj%dlr_f_ptr, SPIR_ORDER_COLUMN_MAJOR, &
    ndim_c, c_loc(input_dims_c), target_dim_c, c_loc(arr), c_loc(res))
  IF (status_c /= 0) THEN
    CALL errore('dlr2ir_{func_suffix}_{ndim}d', 'Error converting DLR to IR', status_c)
  ENDIF
END SUBROUTINE"""
    
    return function

def generate_all_functions():
    """Generate all dlr2ir functions for 1d to 7d with different type combinations."""
    content = []
    
    # Header comment
    content.append("! Auto-generated file - do not edit manually")
    content.append("! Generated by generate_dlr2ir.py")
    content.append("! Based on template from sparseir_ext_expanded_fixed2.F90")
    content.append("")
    
    # Type combinations: (input_type, output_type)
    input_output_types = [('d', 'd'), ('z', 'z')]
    
    # Generate functions for each type combination and dimension
    for input_type, output_type in input_output_types:
        for ndim in range(1, 8):  # 1d to 7d
            function = generate_dlr2ir_function(ndim, input_type, output_type)
            content.append(function)
            content.append("")
    
    return "\n".join(content)

def main():
    """Main function to generate the file."""
    output_file = "dlr2ir_impl.inc"
    
    print(f"Generating {output_file}...")
    
    content = generate_all_functions()
    
    # Write to file
    with open(output_file, 'w') as f:
        f.write(content)
    
    print(f"Successfully generated {output_file}")
    print(f"Total lines: {len(content.splitlines())}")
    print(f"Generated functions for dimensions: 1d to 7d")
    print(f"Type combinations: (d,d) and (z,z)")

if __name__ == "__main__":
    main()
