! Fortran interface for the SparseIR library
! This module provides Fortran bindings to the SparseIR C API using iso_c_binding
module sparseir
  use, intrinsic :: iso_c_binding
  implicit none
  private

  ! Export public interfaces
  !public :: is_assigned
  !include '_public.inc'
  !!include '_public_kernel.inc'
  !include '_public_sve_result.inc'

  ! Enumeration types
  enum, bind(c)
    enumerator :: SPIR_STATISTICS_FERMIONIC = 1
    enumerator :: SPIR_STATISTICS_BOSONIC = 0
  end enum

  include '_fortran_types.inc'

  ! Interface declarations for C API functions
  interface
    ! Type generic procedures (generated by generate_binding.py)
    include '_cbinding.inc'
  end interface

  ! Type specific procedures (manually written)
  !interface
    !!include '_proc_kernel.inc'
    !include '_proc_sve_result.inc'
    !include '_proc_finite_temp_basis.inc'
  !end interface

end module sparseir