name: Python C API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libeigen3-dev libopenblas-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install eigen openblas
      - uses: actions/checkout@v5
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.15"
          python-version: ${{ matrix.python-version }}
      - name: Run prepare_build.py
        run: python3 prepare_build.py
        working-directory: python

      - name: Run uv sync
        run: uv sync
        working-directory: python
        env:
          SPARSEIR_USE_BLAS: 1

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
        working-directory: python
        env:
          SPARSEIR_USE_BLAS: 1
