# Multi-platform CMake CI workflow for libsparseir (without BLAS)
# Tests across Windows, macOS, and Ubuntu with gcc and clang compilers
name: CMake Multi-Platform CI (No BLAS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  INSTALL_PREFIX: ${{github.workspace}}/install

jobs:
  build-no-blas:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu with gcc and clang (x86_64)
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            eigen_install: sudo apt update && sudo apt install -y libeigen3-dev
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            eigen_install: sudo apt update && sudo apt install -y libeigen3-dev

          # Ubuntu ARM64 with gcc and clang
          - os: ubuntu-latest
            arch: arm64
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
            eigen_install: sudo apt update && sudo apt install -y libeigen3-dev
          - os: ubuntu-latest
            arch: arm64
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            eigen_install: sudo apt update && sudo apt install -y libeigen3-dev

          # macOS with clang
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            eigen_install: brew install eigen

          # Windows with MSVC and clang
          - os: windows-latest
            compiler: msvc
            c_compiler: cl
            cpp_compiler: cl
            eigen_install: vcpkg install eigen3
          - os: windows-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
            eigen_install: vcpkg install eigen3

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}-no-blas

    steps:
    - uses: actions/checkout@v5

    - name: Set up MSVC (Windows)
      if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
      uses: microsoft/setup-msbuild@v2

    - name: Setup vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        "${{ github.workspace }}\vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Fortran compiler (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install gfortran

    - name: Install Eigen
      run: ${{ matrix.eigen_install }}

    - name: Debug Fortran compilers (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo "Available Fortran compilers:"
        ls -la /opt/homebrew/bin/*fortran* || echo "No *fortran* found in /opt/homebrew/bin/"
        ls -la /usr/local/bin/*fortran* || echo "No *fortran* found in /usr/local/bin/"
        which gfortran || echo "gfortran not in PATH"
        which gfortran-13 || echo "gfortran-13 not in PATH"

    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          # Use the full path to gfortran from Homebrew gcc
          FORTRAN_COMPILER="/opt/homebrew/bin/gfortran-13"
        else
          FORTRAN_COMPILER="gfortran"
        fi

        cmake -B ${{github.workspace}}/build \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_Fortran_COMPILER="$FORTRAN_COMPILER" \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DSPARSEIR_BUILD_FORTRAN=ON \
          -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PREFIX}} \
          -DSPARSEIR_BUILD_TESTING=ON \
          -DSPARSEIR_USE_BLAS=OFF

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cmake -B ${{github.workspace}}/build `
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} `
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -DSPARSEIR_BUILD_FORTRAN=OFF `
          -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PREFIX}} `
          -DSPARSEIR_USE_BLAS=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --build-config ${{env.BUILD_TYPE}} --output-on-failure

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Verify Installation
      run: |
        ls -la ${{env.INSTALL_PREFIX}}/include/sparseir/
        ls -la ${{env.INSTALL_PREFIX}}/lib/
