name: Build and upload conda packages

# Triggered a new tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix .os }}
    strategy:
      matrix:
        # https://github.com/s-weigand/setup-conda/issues/432
        os: [ubuntu-latest, windows-2025, macos-latest]

    steps:
    - uses: actions/checkout@v5
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Install dependencies
      run: |
        conda install conda-build anaconda-client -y

    - name: Bulid and upload
      env:
        ANACONDA_API_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      run: |
        python3 --version
        conda config --set anaconda_upload yes
        conda build conda-recipe --user SpM-lab
