name: Python Build & Publish (Trusted)

on:
  push:
    tags: ["v*"]     # 例: v0.1.0 を push で発火
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "auto"
          #- os: windows-latest
          #  cibw_archs: "AMD64"
          - os: macos-13  # Intel Mac
            cibw_archs: "x86_64"
          - os: macos-latest  # Apple Silicon Mac
            cibw_archs: "arm64"
    steps:
      - uses: actions/checkout@v4
      - name: remove python/.gitignore
        shell: bash
        run: |
          rm -f python/.gitignore
      - uses: pypa/cibuildwheel@v3.1.4
        env:
          CIBW_DEPENDENCY_VERSIONS: "latest"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=11.0"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_SKIP: "*-manylinux_i686 *-musllinux_i686"
          # CIBW_BUILD: "cp312-*"
        with:
          package-dir: ./python
          output-dir: dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.cibw_archs }}
          path: dist/*

  publish-testpypi:
    needs: build-wheels
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write     # ← Trusted Publishing に必須
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Publish to TestPyPI (Trusted)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true
          attestations: false  # Disable attestations due to Sigstore service issues